module UI.Instances (
    module X
) where

import Object.Widget.Node               as X (Node, PendingNode)
import Object.Widget.Connection         as X (Connection, CurrentConnection)
import Object.Widget.Port               as X (Port)
import Object.Widget.Number.Discrete    as X (DiscreteNumber)
import Object.Widget.Number.Continuous  as X (ContinuousNumber)
import Object.Widget.Slider.Discrete    as X (DiscreteSlider)
import Object.Widget.Slider.Continuous  as X (ContinuousSlider)
import Object.Widget.Toggle             as X (Toggle)
import Object.Widget.TextBox            as X (TextBox)
import Object.Widget.LabeledTextBox     as X (LabeledTextBox)
import Object.Widget.Choice.RadioButton as X (RadioButton)
import Object.Widget.Group              as X (Group)
import Object.Widget.List               as X (List)
import Object.Widget.Button             as X (Button)
import Object.Widget.Label              as X (Label)

import UI.Widget.Node                   as X ()
import UI.Widget.Slider                 as X ()
import UI.Widget.Connection             as X ()
import UI.Widget.Port                   as X ()
import UI.Widget.Number.Discrete        as X ()
import UI.Widget.Number.Continuous      as X ()
import UI.Widget.Slider.Discrete        as X ()
import UI.Widget.Slider.Continuous      as X ()
import UI.Widget.Toggle                 as X ()
import UI.Widget.TextBox                as X ()
import UI.Widget.LabeledTextBox         as X ()
import UI.Widget.Choice                 as X ()
import UI.Widget.Choice.RadioButton     as X ()
import UI.Widget.Group                  as X ()
import UI.Widget.List                   as X ()
import UI.Widget.Button                 as X ()
import UI.Widget.Label                  as X ()

import UI.Widget.List.Constructor       as X ()
