{-# OPTIONS_GHC -fno-warn-missing-signatures #-}

module Flowbox.ProjectManager.Topic where



projectListRequest                                     = "project.list.request"
projectLookupRequest                                   = "project.lookup.request"
projectCreateRequest                                   = "project.create.request"
projectOpenRequest                                     = "project.open.request"
projectModifyRequest                                   = "project.modify.request"
projectCloseRequest                                    = "project.close.request"
projectStoreRequest                                    = "project.store.request"
projectLibraryListRequest                              = "project.library.list.request"
projectLibraryLookupRequest                            = "project.library.lookup.request"
projectLibraryCreateRequest                            = "project.library.create.request"
projectLibraryLoadRequest                              = "project.library.load.request"
projectLibraryUnloadRequest                            = "project.library.unload.request"
projectLibraryStoreRequest                             = "project.library.store.request"
projectLibraryAstGetRequest                            = "project.library.ast.get.request"
projectLibraryAstRemoveRequest                         = "project.library.ast.remove.request"
projectLibraryAstResolveRequest                        = "project.library.ast.resolve.request"
projectLibraryAstModuleAddRequest                      = "project.library.ast.module.add.request"
projectLibraryAstModuleModifyClsRequest                = "project.library.ast.module.modify.cls.request"
projectLibraryAstModuleModifyFieldsRequest             = "project.library.ast.module.modify.fields.request"
projectLibraryAstModuleModifyImportsRequest            = "project.library.ast.module.modify.imports.request"
projectLibraryAstDataAddRequest                        = "project.library.ast.data.add.request"
projectLibraryAstDataModifyClassesRequest              = "project.library.ast.data.modify.classes.request"
projectLibraryAstDataModifyClsRequest                  = "project.library.ast.data.modify.cls.request"
projectLibraryAstDataModifyConsRequest                 = "project.library.ast.data.modify.cons.request"
projectLibraryAstDataModifyMethodsRequest              = "project.library.ast.data.modify.methods.request"
projectLibraryAstFunctionAddRequest                    = "project.library.ast.function.add.request"
projectLibraryAstFunctionModifyInputsRequest           = "project.library.ast.function.modify.inputs.request"
projectLibraryAstFunctionModifyNameRequest             = "project.library.ast.function.modify.name.request"
projectLibraryAstFunctionModifyOutputRequest           = "project.library.ast.function.modify.output.request"
projectLibraryAstFunctionModifyPathRequest             = "project.library.ast.function.modify.path.request"
projectLibraryAstFunctionGraphGetRequest               = "project.library.ast.function.graph.get.request"
projectLibraryAstFunctionGraphConnectRequest           = "project.library.ast.function.graph.connect.request"
projectLibraryAstFunctionGraphDisconnectRequest        = "project.library.ast.function.graph.disconnect.request"
projectLibraryAstFunctionGraphLookupRequest            = "project.library.ast.function.graph.lookup.request"
projectLibraryAstFunctionGraphNodeAddRequest           = "project.library.ast.function.graph.node.add.request"
projectLibraryAstFunctionGraphNodeRemoveRequest        = "project.library.ast.function.graph.node.remove.request"
projectLibraryAstFunctionGraphNodeModifyRequest        = "project.library.ast.function.graph.node.modify.request"
projectLibraryAstFunctionGraphNodeModifyinplaceRequest = "project.library.ast.function.graph.node.modifyinplace.request"
projectLibraryAstFunctionGraphNodeDefaultGetRequest    = "project.library.ast.function.graph.node.default.get.request"
projectLibraryAstFunctionGraphNodeDefaultRemoveRequest = "project.library.ast.function.graph.node.default.remove.request"
projectLibraryAstFunctionGraphNodeDefaultSetRequest    = "project.library.ast.function.graph.node.default.set.request"
projectLibraryAstFunctionGraphNodePropertiesGetRequest = "project.library.ast.function.graph.node.properties.get.request"
projectLibraryAstFunctionGraphNodePropertiesSetRequest = "project.library.ast.function.graph.node.properties.set.request"
projectLibraryAstPropertiesGetRequest                  = "project.library.ast.properties.get.request"
projectLibraryAstPropertiesSetRequest                  = "project.library.ast.properties.set.request"

projectmanagerSyncGetRequest = "projectmanager.sync.get.request"
