#!/bin/bash

PACKAGE_DB_GLOB=$(awk -F ": " '/package-db/ {print $2}' cabal.sandbox.config)/../*-ghcjs-*-packages.conf.d
PACKAGE_DB=$(echo $PACKAGE_DB_GLOB) # ugly force expand glob

ghcjs -package-db=$PACKAGE_DB -iapp/src/ --interactive -package base -package ghcjs-base -package ghcjs-dom -package reactive-banana -package text -package transformers -package mtl -package lens -package containers -package random -package pretty-show -XNoImplicitPrelude -XDoAndIfThenElse -XTemplateHaskell -XDeriveGeneric -XStandaloneDeriving -XFlexibleContexts -XMultiParamTypeClasses -XDefaultSignatures -XDeriveFunctor -XDeriveTraversable -XDeriveFoldable -XFlexibleInstances -XLambdaCase -XConstraintKinds -XGeneralizedNewtypeDeriving -XDeriveDataTypeable -XScopedTypeVariables Main  -odir ../../dist/ghcjs -hidir ../../dist/ghcjs

