# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, accelerate, bmp, repa, vector, fetchgit }:

cabal.mkDerivation (self: {
  pname = "accelerate-io";
  version = "0.15.0.0";
  src = fetchgit {
    url = https://github.com/AccelerateHS/accelerate-io.git;
    rev = "6c5108d624b5c1b8090ad189de85155cfb6526dc";
    sha256 = "01blkkfrcal1s7l2vqgcbvdm6am71yw3gxn1wdvlsqh1w5564yvc";
  };
  buildDepends = [ accelerate bmp repa vector ];
  meta = {
    homepage = "https://github.com/AccelerateHS/accelerate-io";
    description = "Read and write Accelerate arrays in various formats";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
