# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, fclabels, hashable, hashtables, unorderedContainers, fetchgit }:

cabal.mkDerivation (self: {
  pname = "accelerate";
  version = "0.15.0.0";
  src = fetchgit {
    url = https://github.com/AccelerateHS/accelerate.git;
    rev = "afe6988dec23ad51465b880673ca7f98c3811fa3";
    sha256 = "1zcbgfayc652flmwany9kkbcnf440jnnp53n25lp03s97p27b6x2";
  };
  buildDepends = [
    fclabels hashable hashtables unorderedContainers
  ];
  meta = {
    homepage = "https://github.com/AccelerateHS/accelerate/";
    description = "An embedded language for accelerated array processing";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
