# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, accelerate, binary, cryptohash, cuda, fclabels, filepath
, hashable, hashtables, languageCQuote, mainlandPretty, mtl
, SafeSemaphore, srcloc, text, transformers, unorderedContainers
, fetchgit
}:

cabal.mkDerivation (self: {
  pname = "accelerate-cuda";
  version = "0.15.0.0";
  src = fetchgit {
    url = https://github.com/AccelerateHS/accelerate-cuda.git;
    rev = "dc39e36c6765a6fec8451bcdbf85ac47aa93e925";
    sha256 = "11p9yc3lgz4g7wj991jwy040fgs9hiy016aaavwbwz5iaxpmpazf";
  };
  buildDepends = [
    accelerate binary cryptohash cuda fclabels filepath hashable
    hashtables languageCQuote mainlandPretty mtl SafeSemaphore srcloc
    text transformers unorderedContainers
  ];
  meta = {
    homepage = "https://github.com/AccelerateHS/accelerate-cuda/";
    description = "Accelerate backend for NVIDIA GPUs";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
