# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, base64Bytestring, conduit, conduitExtra, dataDefault
, hspec, httpConduit, httpTypes, HUnit, iproute, liftedBase
, monadControl, mtl, parallel, parsec, QuickCheck, random
, resourcet, safe, SHA, simpleConfig, strptime, text, time, tls
, transformers, transformersBase, xmlConduit, xmlTypes
}:

cabal.mkDerivation (self: {
  pname = "aws-sdk";
  version = "0.12.4";
  sha256 = "0zmwfkfddiyyn264kay6m295fh23gii8axln1fjykbsdgd6yy5rb";
  buildDepends = [
    base64Bytestring conduit conduitExtra dataDefault httpConduit
    httpTypes iproute liftedBase monadControl mtl parallel parsec
    resourcet safe SHA simpleConfig strptime text time tls transformers
    transformersBase xmlConduit xmlTypes
  ];
  doCheck = false;
  testDepends = [
    conduit hspec httpConduit HUnit iproute liftedBase monadControl
    QuickCheck random resourcet text time tls transformers
  ];
  meta = {
    homepage = "http://worksap-ate.github.com/aws-sdk";
    description = "AWS SDK for Haskell";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
