# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, deepseq, integration }:

cabal.mkDerivation (self: {
  pname = "cubicbezier";
  version = "0.2.0";
  sha256 = "1xrbg2pr41lnw7av38q2w70gi4cv1j8rx5pv3fgfr8qb9i0gd9w7";
  buildDepends = [ deepseq integration ];
  meta = {
    description = "Efficient manipulating of 2D cubic bezier curves";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
