# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, accelerate, lens, linear }:

cabal.mkDerivation (self: {
  pname = "linear-accelerate";
  version = "0.1";
  sha256 = "1b2fpdx6wx5axb7jaqgr34mdl08ij15xnq3r0qds17x9yrb29ml3";
  jailbreak = true;
  buildDepends = [ accelerate lens linear ];
  meta = {
    homepage = "http://github.com/ekmett/linear-accelerate/";
    description = "Instances to use linear vector spaces on accelerate backends";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
