# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, deepseq, QuickCheck }:

cabal.mkDerivation (self: {
  pname = "pretty";
  version = "1.1.1.2";
  sha256 = "0i2n1ymszrrnv8npf3q7g7ccjrgfkfwfj5h83n768ahyrhr118nf";
  buildDepends = [ deepseq ];
  testDepends = [ QuickCheck ];
  doCheck = false;
  meta = {
    homepage = "http://github.com/haskell/pretty";
    description = "Pretty-printing library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
