# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, filepath, mtl, syb, utf8String, fetchgit }:

cabal.mkDerivation (self: {
  pname = "protocol-buffers";
  version = "2.0.14";
  src = fetchgit {
    url = https://github.com/korrix/protocol-buffers.git;
    rev = "03b1ef52494d2a1dfe7ddb6fb3170fd2bfbfa789";
    sha256 = "1ddam0a9jcirqrgyc9h0xqaj2f7nknygfwz3qbpigpln163bqy7f";
  };
  buildDepends = [ binary filepath mtl syb utf8String ];
  meta = {
    homepage = "http://code.haskell.org/protocol-buffers/";
    description = "Parse Google Protocol Buffer specifications";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
