# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, dataDefault, hspec, networkUri, parsec, transformers }:

cabal.mkDerivation (self: {
  pname = "simple-config";
  version = "1.2.2.1";
  sha256 = "1ndczlpqycrmyjm8v3gpsw1f946lfvc70kzmipli4ir9cbqh5d5k";
  buildDepends = [ dataDefault networkUri parsec transformers ];
  testDepends = [ hspec ];
  meta = {
    homepage = "https://github.com/yunomu/simple-config";
    description = "Simple config file parser generator";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
