/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef attrs_CONSTANTS_H
#define attrs_CONSTANTS_H

#include "attrs_types.h"

namespace flowbox { namespace batch {

class attrsConstants {
 public:
  attrsConstants();

};

extern const attrsConstants g_attrs_constants;

}} // namespace

#endif
