/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef batch_CONSTANTS_H
#define batch_CONSTANTS_H

#include "batch_types.h"



class batchConstants {
 public:
  batchConstants();

};

extern const batchConstants g_batch_constants;



#endif
