/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef defs_CONSTANTS_H
#define defs_CONSTANTS_H

#include "defs_types.h"

namespace flowbox { namespace batch {

class defsConstants {
 public:
  defsConstants();

};

extern const defsConstants g_defs_constants;

}} // namespace

#endif
