/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef defs_TYPES_H
#define defs_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include "attrs_types.h"
#include "libs_types.h"
#include "types_types.h"




typedef int32_t DefID;

typedef struct _NodeDefinition__isset {
  _NodeDefinition__isset() : cls(false), libID(false), defID(false), flags(false), attribs(false) {}
  bool cls;
  bool libID;
  bool defID;
  bool flags;
  bool attribs;
} _NodeDefinition__isset;

class NodeDefinition {
 public:

  static const char* ascii_fingerprint; // = "A9431E373B1B9F79D91BA1A7490ED5DC";
  static const uint8_t binary_fingerprint[16]; // = {0xA9,0x43,0x1E,0x37,0x3B,0x1B,0x9F,0x79,0xD9,0x1B,0xA1,0xA7,0x49,0x0E,0xD5,0xDC};

  NodeDefinition() : libID(0), defID(0) {
  }

  virtual ~NodeDefinition() throw() {}

   ::TypeContainer cls;
   ::LibID libID;
  DefID defID;
   ::Flags flags;
   ::Attributes attribs;

  _NodeDefinition__isset __isset;

  void __set_cls(const  ::TypeContainer& val) {
    cls = val;
    __isset.cls = true;
  }

  void __set_libID(const  ::LibID val) {
    libID = val;
    __isset.libID = true;
  }

  void __set_defID(const DefID val) {
    defID = val;
    __isset.defID = true;
  }

  void __set_flags(const  ::Flags& val) {
    flags = val;
    __isset.flags = true;
  }

  void __set_attribs(const  ::Attributes& val) {
    attribs = val;
    __isset.attribs = true;
  }

  bool operator == (const NodeDefinition & rhs) const
  {
    if (__isset.cls != rhs.__isset.cls)
      return false;
    else if (__isset.cls && !(cls == rhs.cls))
      return false;
    if (__isset.libID != rhs.__isset.libID)
      return false;
    else if (__isset.libID && !(libID == rhs.libID))
      return false;
    if (__isset.defID != rhs.__isset.defID)
      return false;
    else if (__isset.defID && !(defID == rhs.defID))
      return false;
    if (__isset.flags != rhs.__isset.flags)
      return false;
    else if (__isset.flags && !(flags == rhs.flags))
      return false;
    if (__isset.attribs != rhs.__isset.attribs)
      return false;
    else if (__isset.attribs && !(attribs == rhs.attribs))
      return false;
    return true;
  }
  bool operator != (const NodeDefinition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NodeDefinition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(NodeDefinition &a, NodeDefinition &b);



#endif
