/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "graph_constants.h"

namespace flowbox { namespace batch { namespace graph {

const graphConstants g_graph_constants;

graphConstants::graphConstants() {
}

}}} // namespace

