/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef graph_TYPES_H
#define graph_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include "attrs_types.h"




struct DefaultValueType {
  enum type {
    StringV = 0,
    IntV = 1
  };
};

extern const std::map<int, const char*> _DefaultValueType_VALUES_TO_NAMES;

struct NodeType {
  enum type {
    Type = 0,
    Call = 1,
    Default = 2,
    New = 3,
    Inputs = 4,
    Outputs = 5,
    Tuple = 6
  };
};

extern const std::map<int, const char*> _NodeType_VALUES_TO_NAMES;

typedef int32_t NodeID;

typedef std::vector<int32_t>  PortDescriptor;

typedef struct _DefaultValue__isset {
  _DefaultValue__isset() : i(false), s(false) {}
  bool i;
  bool s;
} _DefaultValue__isset;

class DefaultValue {
 public:

  static const char* ascii_fingerprint; // = "69ED04DC035A4CF78CE4B470902F18B3";
  static const uint8_t binary_fingerprint[16]; // = {0x69,0xED,0x04,0xDC,0x03,0x5A,0x4C,0xF7,0x8C,0xE4,0xB4,0x70,0x90,0x2F,0x18,0xB3};

  DefaultValue() : cls((DefaultValueType::type)0), i(0), s() {
  }

  virtual ~DefaultValue() throw() {}

  DefaultValueType::type cls;
  int32_t i;
  std::string s;

  _DefaultValue__isset __isset;

  void __set_cls(const DefaultValueType::type val) {
    cls = val;
  }

  void __set_i(const int32_t val) {
    i = val;
    __isset.i = true;
  }

  void __set_s(const std::string& val) {
    s = val;
    __isset.s = true;
  }

  bool operator == (const DefaultValue & rhs) const
  {
    if (!(cls == rhs.cls))
      return false;
    if (__isset.i != rhs.__isset.i)
      return false;
    else if (__isset.i && !(i == rhs.i))
      return false;
    if (__isset.s != rhs.__isset.s)
      return false;
    else if (__isset.s && !(s == rhs.s))
      return false;
    return true;
  }
  bool operator != (const DefaultValue &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DefaultValue & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(DefaultValue &a, DefaultValue &b);

typedef struct _Node__isset {
  _Node__isset() : cls(false), name(false), nodeID(false), flags(false), attrs(false), defVal(false) {}
  bool cls;
  bool name;
  bool nodeID;
  bool flags;
  bool attrs;
  bool defVal;
} _Node__isset;

class Node {
 public:

  static const char* ascii_fingerprint; // = "43F200EE3F1FC1EF3015F9446E707ADF";
  static const uint8_t binary_fingerprint[16]; // = {0x43,0xF2,0x00,0xEE,0x3F,0x1F,0xC1,0xEF,0x30,0x15,0xF9,0x44,0x6E,0x70,0x7A,0xDF};

  Node() : cls((NodeType::type)0), name(), nodeID(0) {
  }

  virtual ~Node() throw() {}

  NodeType::type cls;
  std::string name;
  NodeID nodeID;
   ::Flags flags;
   ::Attributes attrs;
  DefaultValue defVal;

  _Node__isset __isset;

  void __set_cls(const NodeType::type val) {
    cls = val;
    __isset.cls = true;
  }

  void __set_name(const std::string& val) {
    name = val;
    __isset.name = true;
  }

  void __set_nodeID(const NodeID val) {
    nodeID = val;
    __isset.nodeID = true;
  }

  void __set_flags(const  ::Flags& val) {
    flags = val;
    __isset.flags = true;
  }

  void __set_attrs(const  ::Attributes& val) {
    attrs = val;
    __isset.attrs = true;
  }

  void __set_defVal(const DefaultValue& val) {
    defVal = val;
    __isset.defVal = true;
  }

  bool operator == (const Node & rhs) const
  {
    if (__isset.cls != rhs.__isset.cls)
      return false;
    else if (__isset.cls && !(cls == rhs.cls))
      return false;
    if (__isset.name != rhs.__isset.name)
      return false;
    else if (__isset.name && !(name == rhs.name))
      return false;
    if (__isset.nodeID != rhs.__isset.nodeID)
      return false;
    else if (__isset.nodeID && !(nodeID == rhs.nodeID))
      return false;
    if (__isset.flags != rhs.__isset.flags)
      return false;
    else if (__isset.flags && !(flags == rhs.flags))
      return false;
    if (__isset.attrs != rhs.__isset.attrs)
      return false;
    else if (__isset.attrs && !(attrs == rhs.attrs))
      return false;
    if (__isset.defVal != rhs.__isset.defVal)
      return false;
    else if (__isset.defVal && !(defVal == rhs.defVal))
      return false;
    return true;
  }
  bool operator != (const Node &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Node &a, Node &b);

typedef struct _Edge__isset {
  _Edge__isset() : portSrc(false), portDst(false), nodeSrc(false), nodeDst(false) {}
  bool portSrc;
  bool portDst;
  bool nodeSrc;
  bool nodeDst;
} _Edge__isset;

class Edge {
 public:

  static const char* ascii_fingerprint; // = "E3E2F869E2831D70F619B6B13F64FB99";
  static const uint8_t binary_fingerprint[16]; // = {0xE3,0xE2,0xF8,0x69,0xE2,0x83,0x1D,0x70,0xF6,0x19,0xB6,0xB1,0x3F,0x64,0xFB,0x99};

  Edge() : portSrc(0), portDst(0), nodeSrc(0), nodeDst(0) {
  }

  virtual ~Edge() throw() {}

  int32_t portSrc;
  int32_t portDst;
  NodeID nodeSrc;
  NodeID nodeDst;

  _Edge__isset __isset;

  void __set_portSrc(const int32_t val) {
    portSrc = val;
    __isset.portSrc = true;
  }

  void __set_portDst(const int32_t val) {
    portDst = val;
    __isset.portDst = true;
  }

  void __set_nodeSrc(const NodeID val) {
    nodeSrc = val;
    __isset.nodeSrc = true;
  }

  void __set_nodeDst(const NodeID val) {
    nodeDst = val;
    __isset.nodeDst = true;
  }

  bool operator == (const Edge & rhs) const
  {
    if (__isset.portSrc != rhs.__isset.portSrc)
      return false;
    else if (__isset.portSrc && !(portSrc == rhs.portSrc))
      return false;
    if (__isset.portDst != rhs.__isset.portDst)
      return false;
    else if (__isset.portDst && !(portDst == rhs.portDst))
      return false;
    if (__isset.nodeSrc != rhs.__isset.nodeSrc)
      return false;
    else if (__isset.nodeSrc && !(nodeSrc == rhs.nodeSrc))
      return false;
    if (__isset.nodeDst != rhs.__isset.nodeDst)
      return false;
    else if (__isset.nodeDst && !(nodeDst == rhs.nodeDst))
      return false;
    return true;
  }
  bool operator != (const Edge &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Edge & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Edge &a, Edge &b);

typedef struct _Graph__isset {
  _Graph__isset() : nodes(false), edges(false) {}
  bool nodes;
  bool edges;
} _Graph__isset;

class Graph {
 public:

  static const char* ascii_fingerprint; // = "EA2C91D29359A645800FF7F1BA743F1D";
  static const uint8_t binary_fingerprint[16]; // = {0xEA,0x2C,0x91,0xD2,0x93,0x59,0xA6,0x45,0x80,0x0F,0xF7,0xF1,0xBA,0x74,0x3F,0x1D};

  Graph() {
  }

  virtual ~Graph() throw() {}

  std::map<NodeID, Node>  nodes;
  std::vector<Edge>  edges;

  _Graph__isset __isset;

  void __set_nodes(const std::map<NodeID, Node> & val) {
    nodes = val;
    __isset.nodes = true;
  }

  void __set_edges(const std::vector<Edge> & val) {
    edges = val;
    __isset.edges = true;
  }

  bool operator == (const Graph & rhs) const
  {
    if (__isset.nodes != rhs.__isset.nodes)
      return false;
    else if (__isset.nodes && !(nodes == rhs.nodes))
      return false;
    if (__isset.edges != rhs.__isset.edges)
      return false;
    else if (__isset.edges && !(edges == rhs.edges))
      return false;
    return true;
  }
  bool operator != (const Graph &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Graph & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Graph &a, Graph &b);



#endif
