/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef graph_TYPES_H
#define graph_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include "attrs_types.h"




struct NodeType {
  enum type {
    Type = 0,
    Call = 1,
    Default = 2,
    New = 3,
    Inputs = 4,
    Outputs = 5,
    Tuple = 6
  };
};

extern const std::map<int, const char*> _NodeType_VALUES_TO_NAMES;

typedef struct _Node__isset {
  _Node__isset() : cls(false), name(false), flags(false), attrs(false) {}
  bool cls;
  bool name;
  bool flags;
  bool attrs;
} _Node__isset;

class Node {
 public:

  static const char* ascii_fingerprint; // = "2E2E354F61ED971A305E1FF4FAD0A533";
  static const uint8_t binary_fingerprint[16]; // = {0x2E,0x2E,0x35,0x4F,0x61,0xED,0x97,0x1A,0x30,0x5E,0x1F,0xF4,0xFA,0xD0,0xA5,0x33};

  Node() : cls((NodeType::type)0), name() {
  }

  virtual ~Node() throw() {}

  NodeType::type cls;
  std::string name;
   ::Flags flags;
   ::Attributes attrs;

  _Node__isset __isset;

  void __set_cls(const NodeType::type val) {
    cls = val;
    __isset.cls = true;
  }

  void __set_name(const std::string& val) {
    name = val;
    __isset.name = true;
  }

  void __set_flags(const  ::Flags& val) {
    flags = val;
    __isset.flags = true;
  }

  void __set_attrs(const  ::Attributes& val) {
    attrs = val;
    __isset.attrs = true;
  }

  bool operator == (const Node & rhs) const
  {
    if (__isset.cls != rhs.__isset.cls)
      return false;
    else if (__isset.cls && !(cls == rhs.cls))
      return false;
    if (__isset.name != rhs.__isset.name)
      return false;
    else if (__isset.name && !(name == rhs.name))
      return false;
    if (__isset.flags != rhs.__isset.flags)
      return false;
    else if (__isset.flags && !(flags == rhs.flags))
      return false;
    if (__isset.attrs != rhs.__isset.attrs)
      return false;
    else if (__isset.attrs && !(attrs == rhs.attrs))
      return false;
    return true;
  }
  bool operator != (const Node &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Node & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Node &a, Node &b);

typedef struct _Edge__isset {
  _Edge__isset() : src(false), dst(false) {}
  bool src;
  bool dst;
} _Edge__isset;

class Edge {
 public:

  static const char* ascii_fingerprint; // = "989D1F1AE8D148D5E2119FFEC4BBBEE3";
  static const uint8_t binary_fingerprint[16]; // = {0x98,0x9D,0x1F,0x1A,0xE8,0xD1,0x48,0xD5,0xE2,0x11,0x9F,0xFE,0xC4,0xBB,0xBE,0xE3};

  Edge() : src(0), dst(0) {
  }

  virtual ~Edge() throw() {}

  int32_t src;
  int32_t dst;

  _Edge__isset __isset;

  void __set_src(const int32_t val) {
    src = val;
  }

  void __set_dst(const int32_t val) {
    dst = val;
  }

  bool operator == (const Edge & rhs) const
  {
    if (!(src == rhs.src))
      return false;
    if (!(dst == rhs.dst))
      return false;
    return true;
  }
  bool operator != (const Edge &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Edge & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Edge &a, Edge &b);



#endif
