/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef graph_CONSTANTS_H
#define graph_CONSTANTS_H

#include "graph_types.h"

namespace flowbox { namespace batch {

class graphConstants {
 public:
  graphConstants();

};

extern const graphConstants g_graph_constants;

}} // namespace

#endif
