/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "libs_constants.h"

namespace flowbox { namespace batch {

const libsConstants g_libs_constants;

libsConstants::libsConstants() {
}

}} // namespace

