/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef types_TYPES_H
#define types_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>





struct TypeType {
  enum type {
    Undefined = 0,
    Module = 1,
    Function = 2,
    Class = 3,
    Interface = 4,
    Named = 5,
    TypeVariable = 6,
    Tuple = 7,
    List = 8
  };
};

extern const std::map<int, const char*> _TypeType_VALUES_TO_NAMES;

typedef struct _TypeProto__isset {
  _TypeProto__isset() : name(false), items(false), params(false), inputs(false), outputs(false), type(false) {}
  bool name;
  bool items;
  bool params;
  bool inputs;
  bool outputs;
  bool type;
} _TypeProto__isset;

class TypeProto {
 public:

  static const char* ascii_fingerprint; // = "2E68E04A896B98564C800E8EB3D65F7F";
  static const uint8_t binary_fingerprint[16]; // = {0x2E,0x68,0xE0,0x4A,0x89,0x6B,0x98,0x56,0x4C,0x80,0x0E,0x8E,0xB3,0xD6,0x5F,0x7F};

  TypeProto() : cls((TypeType::type)0), name(), inputs(0), outputs(0), type(0) {
  }

  virtual ~TypeProto() throw() {}

  TypeType::type cls;
  std::string name;
  std::vector<int32_t>  items;
  std::vector<int32_t>  params;
  int32_t inputs;
  int32_t outputs;
  int32_t type;

  _TypeProto__isset __isset;

  void __set_cls(const TypeType::type val) {
    cls = val;
  }

  void __set_name(const std::string& val) {
    name = val;
    __isset.name = true;
  }

  void __set_items(const std::vector<int32_t> & val) {
    items = val;
    __isset.items = true;
  }

  void __set_params(const std::vector<int32_t> & val) {
    params = val;
    __isset.params = true;
  }

  void __set_inputs(const int32_t val) {
    inputs = val;
    __isset.inputs = true;
  }

  void __set_outputs(const int32_t val) {
    outputs = val;
    __isset.outputs = true;
  }

  void __set_type(const int32_t val) {
    type = val;
    __isset.type = true;
  }

  bool operator == (const TypeProto & rhs) const
  {
    if (!(cls == rhs.cls))
      return false;
    if (__isset.name != rhs.__isset.name)
      return false;
    else if (__isset.name && !(name == rhs.name))
      return false;
    if (__isset.items != rhs.__isset.items)
      return false;
    else if (__isset.items && !(items == rhs.items))
      return false;
    if (__isset.params != rhs.__isset.params)
      return false;
    else if (__isset.params && !(params == rhs.params))
      return false;
    if (__isset.inputs != rhs.__isset.inputs)
      return false;
    else if (__isset.inputs && !(inputs == rhs.inputs))
      return false;
    if (__isset.outputs != rhs.__isset.outputs)
      return false;
    else if (__isset.outputs && !(outputs == rhs.outputs))
      return false;
    if (__isset.type != rhs.__isset.type)
      return false;
    else if (__isset.type && !(type == rhs.type))
      return false;
    return true;
  }
  bool operator != (const TypeProto &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TypeProto & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(TypeProto &a, TypeProto &b);

typedef struct _Type__isset {
  _Type__isset() : types(false) {}
  bool types;
} _Type__isset;

class Type {
 public:

  static const char* ascii_fingerprint; // = "A7BED1A0E925509A55B985F0FDF15A5D";
  static const uint8_t binary_fingerprint[16]; // = {0xA7,0xBE,0xD1,0xA0,0xE9,0x25,0x50,0x9A,0x55,0xB9,0x85,0xF0,0xFD,0xF1,0x5A,0x5D};

  Type() {
  }

  virtual ~Type() throw() {}

  std::vector<TypeProto>  types;

  _Type__isset __isset;

  void __set_types(const std::vector<TypeProto> & val) {
    types = val;
    __isset.types = true;
  }

  bool operator == (const Type & rhs) const
  {
    if (__isset.types != rhs.__isset.types)
      return false;
    else if (__isset.types && !(types == rhs.types))
      return false;
    return true;
  }
  bool operator != (const Type &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Type & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(Type &a, Type &b);



#endif
