#!/usr/bin/env python
import os
import subprocess
import sys

FLOWBOX_GIT = os.path.join(".git", "flowbox")
PYENV = os.path.join(FLOWBOX_GIT, "pyenv")
PYENV_BIN_PYTHON = os.path.join(PYENV, "bin", "python")
HOOK_DIR = os.path.join(".git", "hooks")

if __name__ == '__main__':
    python_in_env = HOOK_DIR
    argv = [
        PYENV_BIN_PYTHON,
        os.path.join(sys.argv[0] + ".py")
    ]
    argv.extend(sys.argv[1:])
    subprocess.check_call(argv)
