#!/bin/bash

export PATH=`stack path --bin-path`

ghcjs  -package-db $(stack path --snapshot-pkg-db) \
       -package-db $(stack path --local-pkg-db)    \
       -iapp/src/ \
       -DGHCJS_BROWSER \
       --interactive \
       -package base \
       -package ghcjs-base \
       -package ghcjs-dom \
       -package reactive-banana \
       -package text \
       -package transformers \
       -package mtl \
       -package lens \
       -package containers \
       -package random \
       -package pretty-show \
       -package flowbox-utils \
       -package convert \
       -package process \
       -package constraints \
       -package errors \
       -package graphviz \
       -package vector \
       -package luna-tc \
       -package luna-protobuf-old-gen \
       -package flowbox-batch-protobuf \
       -package batch-lib-project-manager-api \
       -XNoImplicitPrelude \
       -XDoAndIfThenElse \
       -XTemplateHaskell \
       -XDeriveGeneric \
       -XStandaloneDeriving \
       -XFlexibleContexts \
       -XMultiParamTypeClasses \
       -XDefaultSignatures \
       -XDeriveFunctor \
       -XDeriveTraversable \
       -XDeriveFoldable \
       -XFlexibleInstances \
       -XLambdaCase \
       -XConstraintKinds \
       -XGeneralizedNewtypeDeriving \
       -XDeriveDataTypeable \
       -XScopedTypeVariables \
       -odir  ../../dist/ghcjs \
       -hidir ../../dist/ghcjs \
       Main
