name:                nodelab
version:             0.1.0.0
synopsis:            NodeLab
homepage:            www.nodelab.io
license:             AllRightsReserved
author:              New Byte Order
maintainer:          contact@nodelab.io

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NoImplicitPrelude
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell

ghc-options:
    -Wall
    -fno-warn-orphans -fno-warn-missing-signatures -fno-warn-name-shadowing

#
# ACHTUNG! Zmieniasz tu - zmien w interactive
#
dependencies:
  - "base >= 4.8 && < 4.9"
  - aeson
  - base64-bytestring
  - binary
  - bytestring
  - constraints
  - containers
  - convert
  - data-default
  - datetime
  - errors
  - fgl
  - ghcjs-base
  - ghcjs-dom
  - ghcjs-prim
  - hashable
  - hsprocessing
  - language-glsl
  - lens
  - luna-empire-api
  - luna-empire-api-json
  - MissingH
  - mtl
  - placeholders
  - pretty-show
  - process
  - prologue
  - random
  - scope-searcher
  - split
  - text
  - time
  - transformers
  - unordered-containers
  - uuid-types
  - vector
  - visualization-api

executables:
  nodelab:
    main:             Main.hs
    source-dirs:      app/src
