#!/usr/bin/python2.7

###########################################################################
## Copyright (C) Flowbox, Inc / All Rights Reserved
## Unauthorized copying of this file, via any medium is strictly prohibited
## Proprietary and confidential
## Flowbox Team <contact@flowbox.io>, 2014
###########################################################################

import os
import os.path
from   subprocess   import call
import sys
from   utils.colors import print_error
import utils.errors as     errors



def main():
    rootPath  = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
    srcDirName  = 'src'
    sboxEnv   = "FDEV_TARGETS"
    os.chdir(rootPath)

    pkgNames = []
    args = []
    for arg in sys.argv[1:]:
        if arg.startswith('--pkgs='):
            pkgNames = arg[7:].split(',')
        else: args.append(arg)

    if not pkgNames:
        if not os.environ.has_key(sboxEnv):
            print_error("Flowbox development environment not initialized.")
            sys.exit(1)

        pkgNames = os.environ[sboxEnv].split(":")

    for pkg in pkgNames:
        src = os.path.join(pkg, srcDirName)
        ret = call('hlint %s --report' % src, shell=True)
        errors.handle_err(ret)

main()


