#!/usr/bin/python2.7

###########################################################################
## Copyright (C) Flowbox, Inc / All Rights Reserved
## Unauthorized copying of this file, via any medium is strictly prohibited
## Proprietary and confidential
## Flowbox Team <contact@flowbox.io>, 2014
###########################################################################

from   config.packages import pkgDb
import sys
import os
import os.path
from   subprocess      import call
import utils.errors    as     errors
from   utils.colors    import print_info, print_error



def main():
    rootPath  = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
    sboxEnv   = "FDEV_TARGETS"
    os.chdir(rootPath)

    pkgNames = []
    args = []
    for arg in sys.argv[1:]:
        if arg.startswith('--pkgs='):
            pkgNames = arg[7:].split(',')
        else: args.append(arg)

    if not pkgNames:
        if not os.environ.has_key(sboxEnv):
            print_error("Flowbox development environment not initialized.")
            sys.exit(1)

        pkgNames = os.environ[sboxEnv].split(":")

    pkgs = [pkgDb[name] for name in pkgNames]

    for pkg in pkgs:
        print_info ("Compiling %s" % pkg.name)

        call("cabal --sandbox=%s/cabal.sandbox.config exec ghci -- -XNoImplicitPrelude "% pkg.sbox, shell=True)


main()


