#!/usr/bin/python2.7

###########################################################################
## Copyright (C) Flowbox, Inc / All Rights Reserved
## Unauthorized copying of this file, via any medium is strictly prohibited
## Proprietary and confidential
## Flowbox Team <contact@flowbox.io>, 2014
###########################################################################

from   config.packages import pkgDb
import os
import os.path
import sys
from   utils.colors import print_warning, print_error
from   utils.errors import handle_out
from   subprocess   import call



def main():
    rootPath  = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
    srcDirName  = 'src'
    sboxEnv   = "FDEV_TARGETS"
    os.chdir(rootPath)

    pkgNames = []
    args = ["--show-details=streaming"]
    for arg in sys.argv[1:]:
        if arg.startswith('--pkgs='):
            pkgNames = arg[7:].split(',')
        else: args.append(arg)

    if not pkgNames:
        if not os.environ.has_key(sboxEnv):
            print_error("Flowbox development environment not initialized.")
            sys.exit(1)

        pkgNames = os.environ[sboxEnv].split(":")

    pkgs = [pkgDb[name] for name in pkgNames]

    cwd = os.getcwd()

    print_warning('If tests are not enabled, run "./scripts/compile -j --enable-tests"')

    for pkg in pkgs:
        os.chdir(pkg.path)
        if not os.path.isfile("cabal.sandbox.config"):
            handle_out(call("cabal sandbox init --sandbox %s" % pkg.sbox, shell=True))
        handle_out(call("cabal test %s" % ' '.join(args), shell=True))

main()


