resolver: lts-4.1

packages:
- ../../libs/batch/plugins/luna-empire
- ../../libs/bus
- ../../libs/bus-binary
- ../../libs/config
- ../../libs/luna-empire
- ../../libs/luna-empire-api
- ../../libs/luna-empire-api-json
- ../../libs/luna/typechecker
- ../../libs/old-utils
- ../../libs/rpc
- ../../libs/utils
- ../../libs/ws-connector
- ../../tools/batch/plugins/broker
- ../../tools/batch/plugins/bus-logger
- ../../tools/batch/plugins/luna-empire
- ../../tools/batch/plugins/ws-connector

extra-deps:
- container-1.0.1
- convert-1.0
- data-construction-1.0
- data-layer-1.0.3
- data-repr-1.0
- docopt-0.7.0.4
- error-util-0.0.1.1
- functor-utils-1.0
- ghc-session-0.1.2.0
- graphviz-2999.18.0.2
- lens-utils-1.0
- prologue-1.0.6
- saltine-0.0.0.4
- string-qq-0.0.2
- typelevel-1.0.2
- cond-0.4.1.1
- tuple-0.3.0.2
- OneTuple-0.2.1

local-bin-path: ../../dist/bin
